[package]
name = "numerical-methods"
version = "0.1.0"
authors = ["Matt Kelly <matthew.kelly2@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
png = "0.16.7"  # TODO:  update this
nalgebra = { version = "0.29", features = [ "serde-serialize" ]}
approx = "0.5.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bincode = "1.3"
chrono = "0.4"